from typing import Protocol
class VectorStore(Protocol):
    model_version: str
    def upsert_attempts(self, attempts): ...
    def similar_attempts(self, text, student_id, skill_id): ...
    def find_resources(self, text, excluded_resource_ids=()): ...
    def counts(self): ...
