from typing import Protocol
from skill_erosion.contracts.models import Attempt, IngestionResult
class AttemptRepository(Protocol):
    def store(self, attempts: list[Attempt]) -> IngestionResult: ...
    def history(self, student_id: str, skill_id: str | None = None) -> list[Attempt]: ...
